/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VPublicIdRouteImport } from './routes/v.$publicId'
import { Route as AuthenticatedVisualizadorRouteImport } from './routes/_authenticated/visualizador'
import { Route as AuthenticatedCriarRouteImport } from './routes/_authenticated/criar'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedBibliotecaRouteImport } from './routes/_authenticated/biblioteca'
import { Route as AuthenticatedCriadorVisualizadorRouteImport } from './routes/_authenticated/criador.visualizador'
import { Route as AuthenticatedCriadorVideoRouteImport } from './routes/_authenticated/criador.video'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VPublicIdRoute = VPublicIdRouteImport.update({
  id: '/v/$publicId',
  path: '/v/$publicId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedVisualizadorRoute =
  AuthenticatedVisualizadorRouteImport.update({
    id: '/visualizador',
    path: '/visualizador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCriarRoute = AuthenticatedCriarRouteImport.update({
  id: '/criar',
  path: '/criar',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedBibliotecaRoute = AuthenticatedBibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCriadorVisualizadorRoute =
  AuthenticatedCriadorVisualizadorRouteImport.update({
    id: '/criador/visualizador',
    path: '/criador/visualizador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCriadorVideoRoute =
  AuthenticatedCriadorVideoRouteImport.update({
    id: '/criador/video',
    path: '/criador/video',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/visualizador': typeof AuthenticatedVisualizadorRoute
  '/v/$publicId': typeof VPublicIdRoute
  '/criador/video': typeof AuthenticatedCriadorVideoRoute
  '/criador/visualizador': typeof AuthenticatedCriadorVisualizadorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/criar': typeof AuthenticatedCriarRoute
  '/visualizador': typeof AuthenticatedVisualizadorRoute
  '/v/$publicId': typeof VPublicIdRoute
  '/criador/video': typeof AuthenticatedCriadorVideoRoute
  '/criador/visualizador': typeof AuthenticatedCriadorVisualizadorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/biblioteca': typeof AuthenticatedBibliotecaRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/criar': typeof AuthenticatedCriarRoute
  '/_authenticated/visualizador': typeof AuthenticatedVisualizadorRoute
  '/v/$publicId': typeof VPublicIdRoute
  '/_authenticated/criador/video': typeof AuthenticatedCriadorVideoRoute
  '/_authenticated/criador/visualizador': typeof AuthenticatedCriadorVisualizadorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/configuracoes'
    | '/criar'
    | '/visualizador'
    | '/v/$publicId'
    | '/criador/video'
    | '/criador/visualizador'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/biblioteca'
    | '/configuracoes'
    | '/criar'
    | '/visualizador'
    | '/v/$publicId'
    | '/criador/video'
    | '/criador/visualizador'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/biblioteca'
    | '/_authenticated/configuracoes'
    | '/_authenticated/criar'
    | '/_authenticated/visualizador'
    | '/v/$publicId'
    | '/_authenticated/criador/video'
    | '/_authenticated/criador/visualizador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  VPublicIdRoute: typeof VPublicIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/v/$publicId': {
      id: '/v/$publicId'
      path: '/v/$publicId'
      fullPath: '/v/$publicId'
      preLoaderRoute: typeof VPublicIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/visualizador': {
      id: '/_authenticated/visualizador'
      path: '/visualizador'
      fullPath: '/visualizador'
      preLoaderRoute: typeof AuthenticatedVisualizadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criar': {
      id: '/_authenticated/criar'
      path: '/criar'
      fullPath: '/criar'
      preLoaderRoute: typeof AuthenticatedCriarRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/biblioteca': {
      id: '/_authenticated/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof AuthenticatedBibliotecaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criador/visualizador': {
      id: '/_authenticated/criador/visualizador'
      path: '/criador/visualizador'
      fullPath: '/criador/visualizador'
      preLoaderRoute: typeof AuthenticatedCriadorVisualizadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/criador/video': {
      id: '/_authenticated/criador/video'
      path: '/criador/video'
      fullPath: '/criador/video'
      preLoaderRoute: typeof AuthenticatedCriadorVideoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBibliotecaRoute: typeof AuthenticatedBibliotecaRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedCriarRoute: typeof AuthenticatedCriarRoute
  AuthenticatedVisualizadorRoute: typeof AuthenticatedVisualizadorRoute
  AuthenticatedCriadorVideoRoute: typeof AuthenticatedCriadorVideoRoute
  AuthenticatedCriadorVisualizadorRoute: typeof AuthenticatedCriadorVisualizadorRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBibliotecaRoute: AuthenticatedBibliotecaRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedCriarRoute: AuthenticatedCriarRoute,
  AuthenticatedVisualizadorRoute: AuthenticatedVisualizadorRoute,
  AuthenticatedCriadorVideoRoute: AuthenticatedCriadorVideoRoute,
  AuthenticatedCriadorVisualizadorRoute: AuthenticatedCriadorVisualizadorRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  VPublicIdRoute: VPublicIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
